### ISSUE TITLE
Orientation of CASU and sensor positions mismatch

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#11]
The IR sensors have labels N, NE, NW, SE, SW, S, which indicate 0,45,135,180,225,270 degrees respectively (according to the comments in `casu.py`).

When a CASU is initialised with yaw=pi/2, the arrow points upwards.  Here, the compass points should be easiest to think about (ie up=North, right=East, etc).  However, in this configuration, the NE and SE sensors are activated when a bee passes on the left hand side -- not the right hand side.

(I believe that the arrow should point forwards, i.e., at 0 degrees, since the bees use this convention)

**Comment by rmm-fcul** [comment]
Is this because the compass points (conventionally) increase clockwise but angles in sine waves increase anti-clockwise?

**Comment by dmiklic** [comment]
This was actually a bug in the simulator. Fixed by larics/assisi-playground@974911a
