### ISSUE TITLE
Deployment crashes if there are no nodes/links in the .nbg file

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#16]
For a single CASU, it isn't clear what should be in the graph file -- but if there are no inter-CASU comms, should the nbg be empty? 

As a workaround, I have used a single self->self link. This does not have a negative influence on behaviour since no messages are received or sent.

**Comment by dmiklic** [comment]
@rmm-fcul can you provide an example (can be in a separate repo)? The system should be able to handle a completely empty .nbg file, or even a "None" instead of a .nbg file in the .assisi project file. This should be strraightforward to implement.

**Comment by rmm-fcul** [comment]
Example deployment attached.  In the .assisi file there are three different .nbg files referenced (two commented out). One works (using a self-link) and two don't (either subgraph is declared or not, but no edges declared).

[example_deployment.tar.gz](https://github.com/larics/assisi-python/files/191231/example_deployment.tar.gz)

**Comment by rmm-fcul** [comment]
I was looking at this again and a more minimal workaround is to use the definition of nodes in .dot, rather than via edges. For example:
```
# simplest assisi graph?
digraph circle {
    subgraph "sim-arena1" {
        "casu-sim-000";
    }
}
```

However, the more general features you mention would be an improvement in robustness/usability.
