### ISSUE TITLE
casu.Casu.get_peltier_setpoint does not work

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#21]
With the physical casus, querying the peltier set value always returns (0, false) even when the casu is heating.  For example:

In [6]: from assisipy import casu
In [7]: c = casu.Casu(rtc_file_name=rtc)
casu-001 connected!

In [8]: c.set_temp(32)
In [9]: c.get_peltier_setpoint()
Out[9]: (0, False)

In [10]: c.temp_standby()
In [11]: c.get_peltier_setpoint()
Out[11]: (0, False)

**Comment by dmiklic** [comment]
@rmm-fcul  please check if this also happens with the simulated CASUs. This will help us localize the source of the error.

**Comment by rmm-fcul** [comment]
In simulation the function seems to work fine; however, the initial state in simulation is heating, which is not accurate to the physical side. 

Example code below (using rtc files generated by deployment tool):

In [13]: c = casu.Casu(rtc_file_name='sim_3x3_local_sandbox/sim-01/casu-001/casu-001.rtc')
casu-001 connected!

In [14]: c.get_peltier_setpoint()
Out[14]: (23.0, True)

In [15]: c.set_temp(36)
In [16]: c.get_peltier_setpoint()
Out[16]: (36.0, True)

In [17]: c.temp_standby()
In [18]: c.get_peltier_setpoint()
Out[18]: (36.0, False)

**Comment by dmiklic** [comment]
@plsm please fix this for simulation (simulated Peltier should start in "off" state); for the hardware side, I have opened larics/assisi-casu-beaglebone#9

**Comment by dmiklic** [comment]
This has been fixed in larics/assisi-casu-beaglebone.
