### ISSUE TITLE
Airflow messages get sent to bees but bee client does not handle them

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#22]
When connecting assisipy.bee.Bee objects to an up-to-date playground, a continuous stream of "unknown device" messages are emitted.

Unknown device AirFlow for Bee north-bee-101
Unknown device AirFlow for Bee north-bee-100
...

**Comment by rmm-fcul** [comment]
I'm testing with assisi-playground branch bee-with-4-temp-sensors, commit 92ef5421ec74b8f195873e6ca0cdc774a7b65f05 (Date:   Mon Jan 11 17:17:12 2016 +0100), and I don't see any error messages as previously reported.  

Additionally, in bee.py[, line 215](https://github.com/larics/assisi-python/blob/master/assisipy/bee.py#L215) handles this message type.

So I think this issue can be closed.

**Comment by dmiklic** [comment]
Closed by 92ef5421 (or before).
