### ISSUE TITLE
deployment tools: Allow extra arguments for the CASU controllers

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#31]
Can we add an option to the `.dep` files that allows a list of additional arguments to be presented to the casu controller? (similar to #20)

I found myself having to edit code or make near-duplicates with different names to mimic what a parameter would usually handle.

**Comment by rmm-fcul** [comment]
I have a candidate solution undergoing testing for this; I'll put a pull request up for review when I'm content with it.

**Comment by dmiklic** [comment]
Closed by f9872ca53b692ccd2a1a27f6bc0f63c26de52116
