### ISSUE TITLE
deployment tools: cleanup of autogenerated files

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#32]
Typically the codebase for a project will be within git or svn, including the deployment setup.  However, executing the deployment tools generates various files.  These transient files should be left out of any repository but sometimes it is hard to know what to ignore.  This leads to either a) a repo with files that it should not have committed, or b) a messy `svn status` / `git status` result. (maybe the repo status is a symptom of a broader issue, not sure)

Is there a straightforward solution to make it easy to know what to ignore?
- option to specify output directory that is not within the project (`latex -output-directory` does this for instance)
- deploy script runnable from a location other than where the `.assisi` file is
- an assisi-clean tool, that removes all the files that it generated once a simulation is over (not logs, obviously)

**Comment by dmiklic** [comment]
I think a combination of .gitignore + a clean tool should do the trick. I'll look into this.

**Comment by plsm** [comment]
Should we include in each repository (svn or git) a file with commands to generate the executable or pdf that automatically puts transient files in temporary folders?

**Comment by dmiklic** [comment]
I think the transient are already in temporary folders. The problem Rob was referring should go away with .gitignore + a "clean" tool. I'll haven't had the time to look at this yet :(

**Comment by rmm-fcul** [comment]
Most of the transient files go into a sandbox directory, `<projname>_sandbox`
but there is also a `<proj>.py` file that is written at the same level as the `<proj>.assisi` file. (then running it creates a .pyc file).

The sandbox is easy enough to ignore but the autogenerated python file is harder to generalise for. 

Any problem to putting the `<proj>.py` inside the sandbox? This would require changes to deploy.py and assisirun.py. Ideally, I'd like a relocatable sandbox, because I don't think this should be where the project files are, but that is another issue...

**Comment by rmm-fcul** [comment]
@dmiklic @plsm  does anyone have any reason against me putting the autogenerated `<proj>.py` file inside the sandbox?

**Comment by plsm** [comment]
> does anyone have any reason against me putting the autogenerated <proj>.py file inside the sandbox?

Autogenerated files should go the sandbox

**Comment by dmiklic** [comment]
Agreed. This does require a small change to the assisirun.py (line 29) in order to let the script find the <proj>.py file (aka. Fabfile).
