### ISSUE TITLE
Deployment tool collect_data.py: allow retrieving results to arbitrary location

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#40]
rather than simply pulling the log files from CASUs to the working directory, allow specification of a target path.

**Comment by rmm-fcul** [comment]
should this allow creation of deep paths? If so, we need `mkdir -p`-like functionality (see http://stackoverflow.com/a/600612) at the start of `collect()` method.

**Comment by dmiklic** [comment]
Yes, this should allow deep paths.

**Comment by rmm-fcul** [comment]
now the PR #48 is merged, should the issue be closed?

**Comment by dmiklic** [comment]
Closed by dfa0382
