### ISSUE TITLE
Deployment tool collect_data.py: allow retrieving arbitrary wildcards rather than just .csv file

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#41]
The assisipy.casu.Casu autologs are .csv files, but custom code might write other files (for instance, calibration or other log formats).  

To generalise, allow for automated retrieval of a list of wildcard patterns and/or specific files. (note: `fab` uses the python glob module, so can be patterns such as '*.csv', 'stage-0?.txt', or 'finalresult.log').

I propose to add the specification in the .dep file, per casu, such as the following:

```
sim-arena1 :
    casu-sim-001 :
        hostname : localhost
        user : assisi
        prefix : deploy
        controller: ../robots/ctrlr.py
        args : [sn30.conf, ]
        extra: [../robots/casu_utils.py, ../config/sn30.conf, ]
        results : ['*.log', '*.calib', ]
```

While it remains more general to specify all results to retrieve, I propose the default behaviour is to *always* attempt to retrieve `.csv` files (and thus not needing to specify in the results list)

**Comment by dmiklic** [comment]
@rmm-fcul I'm waiting on a pull request from you for this, ok?

**Comment by rmm-fcul** [comment]
@dmiklic code is done (see the branch collect_data_arbfiletypes). I'll do some more thorough testing tomorrow and open a PR.
