### ISSUE TITLE
collect_data.py only functions correctly if executed local to the .assisi file

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#46]
Paths are not handled correctly, which means that the tool is inflexible in where it can be executed.

**Comment by dmiklic** [comment]
Will look into this ASAP, as it is actually very relevant to the Arena GUI tool we're working on.

**Comment by rmm-fcul** [comment]
now the PR #47 is merged, should the issue be closed? (it may be worth opening new issues for the other deployment tools if they also suffer similar issues, but that is independent I think)

**Comment by dmiklic** [comment]
Fixed with 836c440
