### ISSUE TITLE
OBSOLETE: ASSISIarenaUI 'hide airflow marker' not working properly

### ISSUE THREAD

**Issue by mbodi** [larics/assisi-python#53]
When clicking on 'hide airflow marker', the temperature markers dissapear.... instead of the airflow markers

**Comment by mbodi** [comment]
is obsolete, stupid me opend the issue in the wrong place. Don't know how to delete it! Sorry!

**Comment by dmiklic** [comment]
Duplicate of larics/assisi-arena-ui#35
