### ISSUE TITLE
Clean up deployment from pre-package leftovers

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-python#54]
Remove the line 

`export PYTHONPATH=/home/assisi/python:$PYTHONPATH;`

from `assisirun.py` (it's a leftover of ancient times, before we had the nice package)

**Comment by rmm-fcul** [comment]
Careful to test for a local installation (e.g. with `pip install --user assisipy`); I think it would work ok provided assisipy is installed in this way for the assisi user as well (and possibly needs `~/.local/bin` added to the path for the scripts, not sure whether deployment tools use any others at runtime)

**Comment by dmiklic** [comment]
Closed by  2e989dd 
The fix assumes a system-wide installation of the assisipy library.
