### ISSUE TITLE
casu.stop() crashes because vibration_standby() is not implemented

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-python#57]
casu.py, line 330 is the culprit.

At least a `def vibration_standby(): pass` implementation would be a good idea.

**Comment by rmm-fcul** [comment]
It seems that `light_standby()` is not implemented either.  Closely enough related to be same issue IMO

**Comment by dmiklic** [comment]
Thanks for catching this Rob, will fix asap.
