### ISSUE TITLE
Extend CASU API with ir_standby

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-python#61]
Corresponding changes need to be made to larics/assisi-playground, larics/assisi-casu-beaglebone and larics/assisi-casu-pic

@kgrip @thaus88 @dmirkovic Please open appropriate issues.

**Comment by dmirkovic** [comment]
Related issues on assisi-casu-pic and assisi-casu-beaglebone resolved.
Issue can be closed after #63 pull request is merged.

**Comment by dmiklic** [comment]
Closed by #63

**Comment by dmiklic** [comment]
Closed by #63
