### ISSUE TITLE
Extend CASU API with set_vibration_pattern method

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-python#70]
Proposed prototype:

`casu.set_vibration_pattern(frequencies, amplitudes, periods, repeat=True)`

The first three parameters are arrays of the same size.

**Comment by dmiklic** [comment]
Requires the implementation of:

- larics/assisi-casu-pic#3
- larics/assisi-msg#2
- larics/assisi-casu-beaglebone#17

**Comment by plsm** [comment]
To implement this, both the playground and the casu beaglebone driver(?) have to cyclically process these arrays in order to set the frequency and amplitude of the vibration.

Another alternative would be a thread on the client side that processes these arrays.

**Comment by dmiklic** [comment]
Client-side thread is not an acceptable solution, as the requirement is to have stable patterns with 100ms and better period resolution, so it has to be implemented on the CASU firmware itself (in real-time).

For me it's ok if this feature is not exactly implemented in the simulator (e.g. we can just take the first frequency in the array and simulate that, or even better, perfrom FFT on the pattern and simulate that). The controllers for the simulated bees can then be adjusted accordingly.

**Comment by plsm** [comment]
What will be the maximum size of these arrays?
If the user passes a bigger array, I would throw an exception.

**Comment by dmiklic** [comment]
It can be whatever we agree on. The partners from UNIGRAZ should specify a reasonable requirement.

I think throwing an exception on oversized arrays is a bit extreme. You should just ignore elements beyond a fixed size that we agree upon. I'll make sure on the Python side that the array is properly sized (and warn the user if he tries to pass an array that's too big)

**Comment by dmiklic** [comment]
Closed by 5db6694

The new API is documented [here](http://assisipy.readthedocs.io/en/latest/assisipy.html#module-assisipy.casu)
